CREATE USER C##SERVER IDENTIFIED BY SERVER;

GRANT RESOURCE, CONNECT, UNLIMITED TABLESPACE TO C##SERVER;


-----------------------------------------------------------------

DROP TABLE NOTICE;
DROP TABLE MEMBER;

DROP SEQUENCE SEQ_UNO;      -- 회원번호 발생시킬 시퀀스
DROP SEQUENCE SEQ_NNO;      -- 공지사항번호 발생시킬 시퀀스

--------------------------------------------------
--------------     MEMBER 관련   ------------------   
--------------------------------------------------

CREATE TABLE MEMBER (
  USER_NO NUMBER PRIMARY KEY,               
  USER_ID VARCHAR2(30) NOT NULL UNIQUE,   
  USER_PWD VARCHAR2(100) NOT NULL,  
  USER_NAME VARCHAR2(15) NOT NULL,  
  PHONE VARCHAR2(13),              
  EMAIL VARCHAR2(100),            
  ADDRESS VARCHAR2(100),
  INTEREST VARCHAR2(100),
  ENROLL_DATE DATE DEFAULT SYSDATE,
  MODIFY_DATE DATE DEFAULT SYSDATE,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN MEMBER.USER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '회원명';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.INTEREST IS '취미';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '정보수정일';
COMMENT ON COLUMN MEMBER.STATUS IS '상태값(Y/N)';

CREATE SEQUENCE SEQ_UNO
NOCACHE;

INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL, 'admin', '1234', '관리자', '010-1111-2222', 'admin@kh.or.kr', '서울시 강남구 역삼동', NULL, SYSDATE, SYSDATE, DEFAULT);

INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL, 'user01', 'pass01', '홍길동', '010-3333-4444', 'user01@kh.or.kr', '서울시 양천구 목동', NULL, SYSDATE, SYSDATE, DEFAULT);

INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL, 'user02', 'pass02', '김말똥', '010-7444-1234', 'user02@kh.or.kr', '서울시 강서구', NULL, SYSDATE, SYSDATE, DEFAULT);


--------------------------------------------------
--------------     NOTICE 관련   -------------------
--------------------------------------------------

CREATE TABLE NOTICE(
  NOTICE_NO NUMBER PRIMARY KEY,
  NOTICE_TITLE VARCHAR2(100) NOT NULL,
  NOTICE_CONTENT VARCHAR2(4000) NOT NULL,
  NOTICE_WRITER NUMBER NOT NULL,
  COUNT NUMBER DEFAULT 0,
  CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
  FOREIGN KEY(NOTICE_WRITER) REFERENCES MEMBER(USER_NO)
);

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지사항번호';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '공지사항제목';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '공지사항내용';
COMMENT ON COLUMN NOTICE.NOTICE_WRITER IS '작성자회원번호';
COMMENT ON COLUMN NOTICE.COUNT IS '조회수';
COMMENT ON COLUMN NOTICE.CREATE_DATE IS '작성일';
COMMENT ON COLUMN NOTICE.STATUS IS '상태값(Y/N)';

CREATE SEQUENCE SEQ_NNO
NOCACHE;

INSERT INTO NOTICE
VALUES (SEQ_NNO.NEXTVAL, '첫번째 공지사항입니다.', '첫번째 공지사항 내용입니다.', 1, DEFAULT, '2020-02-10', DEFAULT);

INSERT INTO NOTICE
VALUES (SEQ_NNO.NEXTVAL, '두번째 공지사항입니다.', '두번째 공지사항 내용입니다.', 1, DEFAULT, '2020-02-21', DEFAULT);
