-- 1
SELECT 
    STUDENT_NO AS 학번,
    STUDENT_NAME AS 이름,
    TO_CHAR(ENTRANCE_DATE, 'RRRR-MM-DD') AS 입학연도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE;

-- 2
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE NOT LENGTH(PROFESSOR_NAME) = 3;

-- 3
SELECT 
    PROFESSOR_NAME AS 교수이름,
    EXTRACT (YEAR FROM SYSDATE) - TO_NUMBER('19'||SUBSTR(PROFESSOR_SSN, 1, 2)) AS 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY 2;

-- 4
SELECT 
    SUBSTR(PROFESSOR_NAME, 2) AS 이름
FROM TB_PROFESSOR;

-- 5
-- 재수생 입학자 
-- 입학연도의 나이가 20살 이상일때 
SELECT 
    STUDENT_NO,
    STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) 
      - EXTRACT (YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6))) >= 20 ;


-- 6
-- 2020년 크리스마스 ??
SELECT 
    TO_CHAR(TO_DATE('20/12/25'), 'DAY')
FROM DUAL;

-- 7
-- TO_DATE('99/10/11','YY/MM/DD'), TO_DATE('49/10/11','YY/MM/DD')
-- TO_DATE('99/10/11','RR/MM/DD'), TO_DATE('49/10/11','RR/MM/DD')

SELECT 
    TO_DATE('99/10/11','YY/MM/DD'), 
    TO_DATE('49/10/11','YY/MM/DD'),
    TO_DATE('99/10/11','RR/MM/DD'), 
    TO_DATE('49/10/11','RR/MM/DD')
FROM DUAL;

-- 8 
SELECT 
    STUDENT_NO,
    STUDENT_NAME
FROM TB_STUDENT
WHERE NOT SUBSTR(STUDENT_NO,1,1) = 'A';
--WHERE STUDENT_NO NOT LIKE 'A%';


-- 9 STUDENT_NO = 'A517178',
SELECT 
    ROUND(AVG(POINT),1) AS 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10
-- 학과별 학생수, "학과번호", "학생수(명)"
SELECT 
    DEPARTMENT_NO AS 학과번호,
    COUNT (*) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

-- 11 지도교수 배정 받지 못한 학생 수 
SELECT 
    COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12 
-- STUDENT_NO = 'A112113', 연도별 평점 
SELECT 
    SUBSTR(TERM_NO,1,4) AS 연도,
    ROUND(AVG(POINT),1) AS "연도별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4);

-- 13
-- 학과별 휴학생 수 
SELECT
    DEPARTMENT_NO AS 학과코드명,
    COUNT (DECODE (ABSENCE_YN, 'Y', 1)) 휴학생수 
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO;
GROP BY 1;


-- 14 동명이인 찾기 
SELECT 
    STUDENT_NAME AS 동일이름, COUNT(*)
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1;


-- 15 
-- STUDENT_NO = 'A112113', 연도, 학기, 학기별 평점, 연도별 누적 평점, 총 평점
SELECT
    SUBSTR(TERM_NO, 1, 4) 년도,
    SUBSTR(TERM_NO, 5, 2) 학기,
    ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO, 1, 4),SUBSTR(TERM_NO, 5, 2))
ORDER BY 1;

/*
-- 15.
SELECT SUBSTR(TERM_NO,1,4) 년도,
       SUBSTR(TERM_NO,5,2) 학기,
       ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2)
UNION ALL 
SELECT SUBSTR(TERM_NO,1,4) 년도,
       NULL,
       ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
UNION ALL
SELECT NULL,
       NULL,
       ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
ORDER BY 년도, 2
;
SELECT SUBSTR(TERM_NO,1,4) 년도,
       SUBSTR(TERM_NO,5,2) 학기,
       ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2))
ORDER BY 1;
*/







